export const dataProperties = [
  {
    id: 1,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie1.jpeg",
    star: 4.5,
    meters: 430,
    description:
      "In the heart of the charming city of Cuenca, we present you a unique opportunity to acquire a spectacular 75-square-meter apartment that combines comfort, elegance, and an unparalleled natural environment. This home, located in a quiet and well-connected area, is a refuge of peace and beauty that will surely captivate you. Upon entering this cozy home, you are welcomed by a spacious hallway that leads to a full bathroom with a bathtub, perfect for relaxing after a long day. Continuing, you will find a generous living-dining room that merges with the kitchen through sliding doors.",
  },
  {
    id: 2,
    location: "Cuenca, Valencia, ES",
    price: 150000,
    bedrooms: 2,
    bathroom: 2,
    image: "propertie2.jpeg",
    star: 4,
    meters: 230,
    description:
      "In the heart of the charming city of Cuenca, we present you a unique opportunity to acquire a spectacular 75-square-meter apartment that combines comfort, elegance, and an unparalleled natural environment. This home, located in a quiet and well-connected area, is a refuge of peace and beauty that will surely captivate you. Upon entering this cozy home, you are welcomed by a spacious hallway that leads to a full bathroom with a bathtub, perfect for relaxing after a long day. Continuing, you will find a generous living-dining room that merges with the kitchen through sliding doors.",
  },
  {
    id: 3,
    location: "Cuenca, Valencia, ES",
    price: 350000,
    bedrooms: 5,
    bathroom: 2,
    image: "propertie3.jpeg",
    star: 5,
    meters: 90,
    description:
      "In the heart of the charming city of Cuenca, we present you a unique opportunity to acquire a spectacular 75-square-meter apartment that combines comfort, elegance, and an unparalleled natural environment. This home, located in a quiet and well-connected area, is a refuge of peace and beauty that will surely captivate you. Upon entering this cozy home, you are welcomed by a spacious hallway that leads to a full bathroom with a bathtub, perfect for relaxing after a long day. Continuing, you will find a generous living-dining room that merges with the kitchen through sliding doors.",
  },
  {
    id: 4,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie4.jpeg",
    star: 4.2,
    meters: 120,
    description:
      "In the heart of the charming city of Cuenca, we present you a unique opportunity to acquire a spectacular 75-square-meter apartment that combines comfort, elegance, and an unparalleled natural environment. This home, located in a quiet and well-connected area, is a refuge of peace and beauty that will surely captivate you. Upon entering this cozy home, you are welcomed by a spacious hallway that leads to a full bathroom with a bathtub, perfect for relaxing after a long day. Continuing, you will find a generous living-dining room that merges with the kitchen through sliding doors.",
  },
  {
    id: 5,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie5.jpeg",
    star: 4.1,
    meters: 87,
    description:
      "In the heart of the charming city of Cuenca, we present you a unique opportunity to acquire a spectacular 75-square-meter apartment that combines comfort, elegance, and an unparalleled natural environment. This home, located in a quiet and well-connected area, is a refuge of peace and beauty that will surely captivate you. Upon entering this cozy home, you are welcomed by a spacious hallway that leads to a full bathroom with a bathtub, perfect for relaxing after a long day. Continuing, you will find a generous living-dining room that merges with the kitchen through sliding doors.",
  },
  {
    id: 6,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie6.jpeg",
    star: 3.7,
    meters: 220,
    description:
      "In the heart of the charming city of Cuenca, we present you a unique opportunity to acquire a spectacular 75-square-meter apartment that combines comfort, elegance, and an unparalleled natural environment. This home, located in a quiet and well-connected area, is a refuge of peace and beauty that will surely captivate you. Upon entering this cozy home, you are welcomed by a spacious hallway that leads to a full bathroom with a bathtub, perfect for relaxing after a long day. Continuing, you will find a generous living-dining room that merges with the kitchen through sliding doors.",
  },
  {
    id: 7,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie7.jpeg",
    star: 4.5,
    meters: 430,
    description:
      "In the heart of the charming city of Cuenca, we present you a unique opportunity to acquire a spectacular 75-square-meter apartment that combines comfort, elegance, and an unparalleled natural environment. This home, located in a quiet and well-connected area, is a refuge of peace and beauty that will surely captivate you. Upon entering this cozy home, you are welcomed by a spacious hallway that leads to a full bathroom with a bathtub, perfect for relaxing after a long day. Continuing, you will find a generous living-dining room that merges with the kitchen through sliding doors.",
  },
  {
    id: 8,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie8.jpeg",
    star: 4.5,
    meters: 330,
    description:
      "In the heart of the charming city of Cuenca, we present you a unique opportunity to acquire a spectacular 75-square-meter apartment that combines comfort, elegance, and an unparalleled natural environment. This home, located in a quiet and well-connected area, is a refuge of peace and beauty that will surely captivate you. Upon entering this cozy home, you are welcomed by a spacious hallway that leads to a full bathroom with a bathtub, perfect for relaxing after a long day. Continuing, you will find a generous living-dining room that merges with the kitchen through sliding doors.",
  },
  {
    id: 9,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie9.jpeg",
    star: 4.5,
    meters: 380,
    description:
      "In the heart of the charming city of Cuenca, we present you a unique opportunity to acquire a spectacular 75-square-meter apartment that combines comfort, elegance, and an unparalleled natural environment. This home, located in a quiet and well-connected area, is a refuge of peace and beauty that will surely captivate you. Upon entering this cozy home, you are welcomed by a spacious hallway that leads to a full bathroom with a bathtub, perfect for relaxing after a long day. Continuing, you will find a generous living-dining room that merges with the kitchen through sliding doors.",
  },
  {
    id: 10,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie10.jpeg",
    star: 4.1,
    meters: 270,
    description:
      "In the heart of the charming city of Cuenca, we present you a unique opportunity to acquire a spectacular 75-square-meter apartment that combines comfort, elegance, and an unparalleled natural environment. This home, located in a quiet and well-connected area, is a refuge of peace and beauty that will surely captivate you. Upon entering this cozy home, you are welcomed by a spacious hallway that leads to a full bathroom with a bathtub, perfect for relaxing after a long day. Continuing, you will find a generous living-dining room that merges with the kitchen through sliding doors.",
  },
  {
    id: 11,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie11.jpeg",
    star: 5,
    meters: 430,
    description:
      "In the heart of the charming city of Cuenca, we present you a unique opportunity to acquire a spectacular 75-square-meter apartment that combines comfort, elegance, and an unparalleled natural environment. This home, located in a quiet and well-connected area, is a refuge of peace and beauty that will surely captivate you. Upon entering this cozy home, you are welcomed by a spacious hallway that leads to a full bathroom with a bathtub, perfect for relaxing after a long day. Continuing, you will find a generous living-dining room that merges with the kitchen through sliding doors.",
  },
  {
    id: 12,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie12.jpeg",
    star: 3.9,
    meters: 76,
    description:
      "In the heart of the charming city of Cuenca, we present you a unique opportunity to acquire a spectacular 75-square-meter apartment that combines comfort, elegance, and an unparalleled natural environment. This home, located in a quiet and well-connected area, is a refuge of peace and beauty that will surely captivate you. Upon entering this cozy home, you are welcomed by a spacious hallway that leads to a full bathroom with a bathtub, perfect for relaxing after a long day. Continuing, you will find a generous living-dining room that merges with the kitchen through sliding doors.",
  },
  {
    id: 13,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie13.jpeg",
    star: 4.8,
    meters: 290,
    description:
      "In the heart of the charming city of Cuenca, we present you a unique opportunity to acquire a spectacular 75-square-meter apartment that combines comfort, elegance, and an unparalleled natural environment. This home, located in a quiet and well-connected area, is a refuge of peace and beauty that will surely captivate you. Upon entering this cozy home, you are welcomed by a spacious hallway that leads to a full bathroom with a bathtub, perfect for relaxing after a long day. Continuing, you will find a generous living-dining room that merges with the kitchen through sliding doors.",
  },
  {
    id: 14,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie14.jpeg",
    star: 4.9,
    meters: 180,
    description:
      "In the heart of the charming city of Cuenca, we present you a unique opportunity to acquire a spectacular 75-square-meter apartment that combines comfort, elegance, and an unparalleled natural environment. This home, located in a quiet and well-connected area, is a refuge of peace and beauty that will surely captivate you. Upon entering this cozy home, you are welcomed by a spacious hallway that leads to a full bathroom with a bathtub, perfect for relaxing after a long day. Continuing, you will find a generous living-dining room that merges with the kitchen through sliding doors.",
  },
  {
    id: 15,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie15.jpeg",
    star: 4.1,
    meters: 287,
    description:
      "In the heart of the charming city of Cuenca, we present you a unique opportunity to acquire a spectacular 75-square-meter apartment that combines comfort, elegance, and an unparalleled natural environment. This home, located in a quiet and well-connected area, is a refuge of peace and beauty that will surely captivate you. Upon entering this cozy home, you are welcomed by a spacious hallway that leads to a full bathroom with a bathtub, perfect for relaxing after a long day. Continuing, you will find a generous living-dining room that merges with the kitchen through sliding doors.",
  },
  {
    id: 16,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie16.jpeg",
    star: 4,
    meters: 290,
    description:
      "In the heart of the charming city of Cuenca, we present you a unique opportunity to acquire a spectacular 75-square-meter apartment that combines comfort, elegance, and an unparalleled natural environment. This home, located in a quiet and well-connected area, is a refuge of peace and beauty that will surely captivate you. Upon entering this cozy home, you are welcomed by a spacious hallway that leads to a full bathroom with a bathtub, perfect for relaxing after a long day. Continuing, you will find a generous living-dining room that merges with the kitchen through sliding doors.",
  },
];